"use client";
import { DEFAULT_PRODUCT_TEMPLATE, renderMessageTemplate, templateVariables } from "@achadinhos/shared";
import { useRouter } from "next/navigation";
import { useState } from "react";
type TemplateRow = { id: string; name: string; platform: "WHATSAPP" | "TELEGRAM" | "BOTH"; content: string; isDefault: boolean; isActive: boolean };
export function TemplateEditor({ templates }: { templates: TemplateRow[] }) { const router = useRouter(); const [editingId, setEditingId] = useState<string>(); const [name, setName] = useState("Modelo de oferta"); const [platform, setPlatform] = useState<TemplateRow["platform"]>("BOTH"); const [content, setContent] = useState(DEFAULT_PRODUCT_TEMPLATE); const [isDefault, setDefault] = useState(true); const [notice, setNotice] = useState(""); const preview = renderMessageTemplate(content, { titulo: "Produto em promoção", precoAtual: "79,90", link: "https://loja.example/oferta", marketplace: "Shopee" });
  function edit(item: TemplateRow) { setEditingId(item.id); setName(item.name); setPlatform(item.platform); setContent(item.content); setDefault(item.isDefault); }
  async function save() { const response = await fetch(editingId ? `/api/templates/${editingId}` : "/api/templates", { method: editingId ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, platform, content, isDefault, isActive: true }) }); const data = await response.json() as { error?: string }; setNotice(data.error ?? "Modelo salvo."); if (response.ok) router.refresh(); }
  return <main className="page-content"><header className="page-heading"><div><span className="eyebrow">CONTEÚDO</span><h1>Modelos de mensagens</h1><p>Crie textos reutilizáveis sem executar código.</p></div></header><div className="template-layout"><section className="content-card template-list"><h2>Seus modelos</h2>{templates.length ? templates.map((item) => <button key={item.id} onClick={() => edit(item)} className={editingId === item.id ? "active" : ""}><span>{item.name}</span><small>{item.platform}{item.isDefault ? " · padrão" : ""}</small></button>) : <p>Nenhum modelo salvo.</p>}</section><section className="content-card template-form"><div className="form-grid"><label>NOME<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>PLATAFORMA<select value={platform} onChange={(event) => setPlatform(event.target.value as typeof platform)}><option value="BOTH">Ambas</option><option value="WHATSAPP">WhatsApp</option><option value="TELEGRAM">Telegram</option></select></label><label className="wide">CONTEÚDO<textarea rows={18} value={content} onChange={(event) => setContent(event.target.value)} /></label></div><div className="variable-chips">{templateVariables.map((variable) => <button key={variable} onClick={() => setContent((current) => `${current}{{${variable}}}`)}>{`{{${variable}}}`}</button>)}</div><label className="default-check"><input type="checkbox" checked={isDefault} onChange={(event) => setDefault(event.target.checked)} /> Modelo padrão para a plataforma</label>{notice && <div className="form-message success">{notice}</div>}<div className="editor-actions"><button className="primary" onClick={() => void save()}>Salvar modelo</button></div></section><section className="content-card template-preview"><span className="eyebrow">PRÉVIA SEGURA</span><pre>{preview.text}</pre><small>Campos ausentes: {preview.missingFields.join(", ") || "nenhum"}</small></section></div></main>;
}
